// <auto-generated />
namespace TotalControl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedtypeproptosection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedtypeproptosection));
        
        string IMigrationMetadata.Id
        {
            get { return "201905291641467_added type prop to section"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
